# Generated by Django 5.0 on 2024-02-27 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EditUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255, null=True)),
                ('mobile_no', models.CharField(max_length=255, null=True)),
                ('about_me', models.TextField(null=True)),
                ('skills', models.CharField(max_length=200, null=True)),
                ('joining_date', models.CharField(max_length=100, null=True)),
                ('education', models.CharField(max_length=255, null=True)),
                ('university', models.CharField(max_length=66, null=True)),
                ('priveus_job', models.CharField(max_length=70, null=True)),
                ('projects', models.CharField(max_length=200, null=True)),
                ('project_desc', models.CharField(max_length=200, null=True)),
                ('interests', models.CharField(max_length=200)),
                ('gender', models.CharField(default='None', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('industry', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('contact_no', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=150)),
                ('location', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255, null=True)),
                ('job_location', models.CharField(max_length=255, null=True)),
                ('job_description', models.TextField(null=True)),
                ('skills_required', models.CharField(max_length=200, null=True)),
                ('posting_date', models.CharField(max_length=100, null=True)),
                ('salary', models.CharField(max_length=255, null=True)),
                ('industry', models.CharField(max_length=66, null=True)),
                ('education', models.CharField(max_length=70, null=True)),
                ('experience_required', models.CharField(max_length=200, null=True)),
                ('gender', models.CharField(max_length=200, null=True)),
                ('company_name', models.CharField(default='Company Name', max_length=200)),
                ('name', models.CharField(default=' Name', max_length=200)),
                ('mobile_no', models.CharField(default='Mobile Number', max_length=200)),
                ('email', models.EmailField(default='something@gmail.com', max_length=200)),
            ],
        ),
    ]
